Program that reads file and saves data to variables
antunsimic/digitalnivodomjer pull request #9
Opened 2024-04-01 16:29 UTC by DadoCres

Program reads file that is locally saved. Checks for each flag and based on the flag saves data into variables. Each variable contains all data for the substring, eg. it is 3 different names in one variable divided by spaces. We should discuss how to approach this.

2024-04-01 20:49 UTC, fmartinkovic requested changes
Pokušavaj ubuduće pisati komentare uz kod koji smatraš da potencijalno ne bi bio jasan nekome tko prvi puta vidi kod.

Također, budući da je Antun sve zadatke već postavio na hrvatskome, koristi hrvatski jezik u daljnjim commitovima i pull requestovima.

2024-04-01 20:49 UTC, fmartinkovic commented on bankovni_izvodi.py
> +
Ove varijable bi trebale biti liste, a ne čisti stringovi, zbog toga da se kroz njih lakše iterira, samim time da bude trivijalan njihov unos u bazu podataka.

2024-04-01 20:49 UTC, fmartinkovic commented on bankovni_izvodi.py
> +f = open("/home/dado/Downloads/izvod.OTP", "r")
Sadrži li ova datoteka samo jedan izvod ili su to sve datoteke kombinirane u jednu?

Pokušaj ovo modificirati da se iterativno otvaraju sve datoteke koje započinju s "IZV_" ili imaju ekstenziju .OTP, te se otvorena datoteka obrađuje; nove vrijednosti se unašaju u listu. Zatim se otvara druga datoteka imena "IZV_" ili ekstenzije .OTP (...)

2024-04-03 15:13 UTC, DadoCres commented on bankovni_izvodi.py
> +f = open("/home/dado/Downloads/izvod.OTP", "r")
Samo je jedan izvod. Napravio sam ovako jer ocekujem da bude neki "drag and drop" na web aplikaciji pa da prvo istestiramo ovako.

2024-04-03 15:53 UTC, merged